name: 10a-External-Script
on:
  workflow_call:
    inputs:
      name:
        description: 'A name'
        type: string
        required: true
        default: 'Helemaal geweldig'
jobs:
  some_job:
    runs-on: windows-latest
    steps:
      - name: External workflow
        run: |
          echo "This is an external script with name: ${{inputs.name}}"
