name: 7-Jobs-Dep
on: workflow_dispatch

jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Job 1
        run: echo "This is Job 1"
  job2:
    runs-on: windows-latest
    steps:
      - name: Job 2
        run: echo "This is Job 2"
  job3:
    runs-on: windows-latest
    needs: job1
    steps:
      - name: Job 3
        run: echo "This is Job 3, dependent on Job 1"
  job4:
    runs-on: windows-latest
    needs: [job2, job3]
    steps:
      - name: Job 4
        run: echo "This is Job 4, dependent on Job 2 and Job 3"


